### ISSUE TITLE
makeComplete -> noun version

### ISSUE THREAD

**Issue by bonesoul** [CanPacis/affixi#1]
`{makeComplete('Azerbaycan')} `-> Azerbaycanın  
should allow a noun parameter to get the correct usage: Azerbaycan'ın.

Possible though with 
`{'Azerbaycan'}&apos;{getCompleteSuffix('Azerbaycan')}`

**Comment by canpacis** [comment]
`makeComplete` function takes a secondary `boolean` argument for proper nouns, the default is `false`. You can use it like `makeComplete('Azerbaycan', true)`, it returns 'Azerbaycan'ın'. Sorry I forgot to put it into the documentation.

**Comment by bonesoul** [comment]
thanks, I also forgot to check the typings.
