### ISSUE TITLE
locative bug

### ISSUE THREAD

**Issue by bonesoul** [CanPacis/affixi#2]
`makeCase(name_tr, Case.Locative, true)`

Namibya is converted to 'Namibya'nda'

Should be a bug i guess.

**Comment by canpacis** [comment]
Yes it is a bug. Tests were incorrect, please udpate your package to version 0.0.2-0.

**Comment by bonesoul** [comment]
thanks for your fast response

**Comment by canpacis** [comment]
Well, you are the only one actively using this package I suppose 😅. Tell me if you need anything.

**Comment by bonesoul** [comment]
sure, will do so :)

using it on my website.
